name: Beta CI/CD

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: CHECK-OUT GIT REPOSITORY
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: './yarn.lock'
        cache: 'yarn'

    - name: Install packages
      run: yarn --prefer-offline

    - name: Build
      run: yarn build

    - name: Move Build Folder (/dist) to (/www)
      run: \cp -r /root/actions-runner/_work/personal-website/personal-website/dist/* /var/www/personal-website-beta