name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: CHECK-OUT GIT REPOSITORY
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache-dependency-path: './yarn.lock'
      #   cache: 'yarn'

    - name: Install packages
      run: yarn install

    - name: Build
      run: yarn build